version: '3.3'

services:
  db:
    container_name: bookshopdb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
        - 7432:5432